stages:
- deploy



# ============================================================================ #
 pages:
  stage: deploy


  script:
  - ls -la
  artifacts:
    paths:
    - public/
    expire_in: 1 hour
# ============================================================================ #
