stages:
- deploy



# ============================================================================ #
pages:
  stage: deploy
  image: docker.io/debian:12.2
  script:
  # - env
  - sed -i 's/_GIT_COMMIT_ID_/'${CI_COMMIT_SHORT_SHA}'/g' public/index.html
  - sed -i 's/_GIT_COMMIT_TIMESTAMP_/'${CI_COMMIT_TIMESTAMP}'/g' public/index.html
  artifacts:
    paths:
    - public/
    expire_in: 1 hour
# ============================================================================ #
